name: Discord通知新版本

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "255136130"
          username: "松鼠推流 ReplyKit"
          avatar_url: "https://cdn.discordapp.com/attachments/408959437165035521/1484570827084136651/IMG_2318.jpg?ex=69beb5d3&is=69bd6453&hm=c647aecc54560896ba7809342dda70e0442b100125db4b309726b4198f3bca00&"
          content: "項目更新啦 看看改動吧！"
          footer_title: "更新日誌 Changelog"
          reduce_headings: true
