name: iOS Archive & Release via Tag

on:
  workflow_run:
    workflows: ["Check Changes & Trigger Tag"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-26
    env:
      FASTLANE_USER: ${{ secrets.APPID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPPass }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag --sort=-creatordate | head -n1)

          if [ -z "$TAG" ]; then
            echo "❌ No tag found"
            exit 1
          fi

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      
      # 2️⃣ Detect default scheme
      - name: Set default scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo "$scheme_list" | ruby -e "
          require 'json'
          data = JSON.parse(STDIN.read)
          schemes = data['project']['schemes']
          puts schemes.find { |s| s.include?('ReplyKit') } || schemes[0]
          ")

          echo $default > default
          echo Using default scheme: $default

      # 3️⃣ Build & Archive (Unsigned)
      - name: Build & Archive Unsigned
        run: |
          mkdir -p build
          scheme=$(cat default)
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
              filetype="workspace"
              file_to_build=`ls -A | grep -i \\.xcworkspace\$`
          else
              filetype="project"
              file_to_build=`ls -A | grep -i \\.xcodeproj\$`
          fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')

          xcodebuild clean -$filetype "$file_to_build" -scheme "$scheme" -configuration Release
         
    
          xcodebuild archive \
            -$filetype "$file_to_build" \
            -scheme "$scheme" \
            -configuration Release \
            -archivePath $PWD/build/liveApp.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO

            
      # 4️⃣ Export Unsigned IPA using external plist
      - name: Export Unsigned IPA
        run: |
        
          cd build
          cp -r liveApp.xcarchive/Products/Applications/*.app .
          mkdir -p Payload
          mv *.app Payload/

          
          TAG=${TAG}

          zip -r liveApp_${TAG}.ipa Payload

          mv liveApp.xcarchive liveApp_${TAG}.xcarchive

          zip -r liveApp_${TAG}.xcarchive.zip liveApp_${TAG}.xcarchive
          cd ..

          echo "Listing build directory contents"
          ls -al build/
          
          

      - name: Upload Release with merged body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.get_tag.outputs.tag }}
        run: |
          GITHUB_API="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
          
          # 抓取最近 10 次 commit 訊息
          COMMITS=$(git log -n 10 --pretty=format:"- %s (%h)")


          NEW_MESSAGE="Automated unsigned iOS build ${TAG_NAME}
          Updated at $(TZ=Asia/Taipei LANG=zh_TW.UTF-8 date +"%Y/%m/%d %p %H:%M:%S (%A)")
          
          Recent commits:
          
          $COMMITS"

          # 嘗試取得現有 release
          RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          $GITHUB_API/tags/$TAG_NAME)

          RELEASE_ID=$(echo "$RELEASE" | jq -r '.id // empty')

          if [ -n "$RELEASE_ID" ]; then
           # Release 存在 → 合併 body
          
           EXISTING_BODY=$(echo "$RELEASE" | jq -r '.body')
           
           MEGRED_BODY="$EXISTING_BODY
           
           $NEW_MESSAGE"
           

           PAYLOAD=$(jq -n \
              --arg body "$MERGED_BODY" \
              '{body: $body}')
              
           # 更新 Release
           curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            $GITHUB_API/$RELEASE_ID \
           -d "$PAYLOAD"

          else
           # Release 不存在 → 建立 Release

           PAYLOAD=$(jq -n \
                --arg tag "$TAG_NAME" \
                --arg name "$TAG_NAME" \
                --arg body "$NEW_MESSAGE" \
                '{tag_name:$tag, name:$name, body:$body, draft:false, prerelease:false}')


           NEW_BODY=$(echo "$NEW_MESSAGE" | jq -Rs --slurp '.')
          
           curl -X POST \
           -H "Authorization: token $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
           $GITHUB_API \
           -d "$PAYLOAD"
          fi


        
      # 5️⃣ Upload IPA & Archive to Release
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: |
            build/*.ipa
            build/liveApp_${{ steps.get_tag.outputs.tag }}.xcarchive.zip
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
